### ISSUE TITLE
Encoding Issue.

### ISSUE THREAD

**Issue by svenborer** [wetling23/logicmonitor-posh-module#12]
There is an issue with sending data to the API which is not properly encoded. For example:

Add-LogicMonitorDeviceGroup -Properties @{name='Ærgo'; parentId=1}

This will lead to an "401 Authorization Failed" due to using special chars (Æ in this case). This can be avoided explicitly using UTF-8 encoding on the data sent to the API. This applies to multiple cmdlets.

**Comment by wetling23** [comment]
Sven, I have the same problem adding a similar device via the UI:

![image](https://user-images.githubusercontent.com/38230187/133492843-8d84b482-eefb-4182-8f40-c63d3ef4dc11.png)

Are _you_ able to manually create a device called "Ærgo"?

**Comment by svenborer** [comment]
I was talking about a device group for example. Or a device property. I will add the fix later this morning as an example for adding a device group.

**Comment by wetling23** [comment]
Okay, I merged your change and added it to other, relevant cmdlets. I have published 1.0.1.81 with those changes (and some others).
