### ISSUE TITLE
Does not work on Linux+pwsh

### ISSUE THREAD

**Issue by iehrenwaldDK** [wetling23/logicmonitor-posh-module#15]
When attempting to run these modules on pwsh 7.1 on Ubuntu 20.04, they all fail with:
Exception calling "GetCurrent" with "0" argument(s): "Windows Principal functionality is not supported on this platform."

Looking at this code, it is:
([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)

Is there a platform-agnostic way to do this?

**Comment by wetling23** [comment]
I added $([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform([System.Runtime.InteropServices.OSPlatform]::Windows)) to check. If the value is false, the module will not run ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator). That oughta do it. This will be released in 1.0.2.7
