### ISSUE TITLE
Choose an open source license for this project

### ISSUE THREAD

**Issue by qrokodial** [wetling23/logicmonitor-posh-module#16]
I can't seem to find the license information for this project, which makes me hesitant to attempt to use it.

If you're unfamiliar with what I mean by this, [take a look at this page that describes the "No License" default policy](https://choosealicense.com/no-permission/).

I'd appreciate it if you'd consider adopting a license for this project so the terms of use are clearly defined.  I personally suggest a license such as [MIT](https://choosealicense.com/licenses/mit/) or [Apache](https://choosealicense.com/licenses/apache-2.0/).

**Comment by wetling23** [comment]
I think I have correctly added the MIT license. I will leave the issue open for a bit, for feedback.
