### ISSUE TITLE
Start-LogicMonitorDeviceSdt - Unexpected error after upgrade to 2023.08.27.0

### ISSUE THREAD

**Issue by Collisionc** [wetling23/logicmonitor-posh-module#26]
Reverting to 2023.04.28.0 as a temporary workaround fixes this. 

Command used:
$LogicMonDevice = Get-LogicMonitorDevice -AccessId $LogicMonitorAccessID -AccessKey $LogicMonitorAccessKey -AccountName $accountname -DisplayName $displayname
Start-LogicMonitorDeviceSdt -AccessId $LogicMonitorAccessID -AccessKey $LogicMonitorAccessKey -AccountName $accountname                      -Id $LogicMonDevice.id -Duration 07:00:00 -Comment "7 Day New Build SDT"

Resulting error:
Out-PsLogging : [ERROR] 2023-08-29T16:30:41: Unexpected error starting SDT. To prevent errors,
Start-LogicMonitorDeviceSdt will exit. If present, the following details were returned:
                Error message: Request body is mandatory
                Error code: 1400
                Invoke-Request: The remote server returned an error: (400) Bad Request.
                Headers:
Name                           Value
----                           -----
Authorization                  LMv1 (redacted)...
Content-Type                   application/json
X-Version                      3
                Body:
At C:\Program Files\WindowsPowerShell\Modules\LogicMonitor\2023.8.27.0\LogicMonitor.psm1:16682 char:21               + ...             Out-PsLogging @loggingParams -MessageType Error -Message  ...                                      +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                              + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException                                       + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Out-PsLogging

**Comment by wetling23** [comment]
Applied fix. Thanks.
