### ISSUE TITLE
Cannot choose collectorSize on Get-LogicMonitorCollectorInstaller

### ISSUE THREAD

**Issue by andy68man** [wetling23/logicmonitor-posh-module#5]
Hello,

Big fan of these PowerShell commands, they've really helped our automated deployment of LogicMonitor collectors, thanks for writing them!

According to the API, it's possible to choose the collectorSize during the download: https://www.logicmonitor.com/support/rest-api-developers-guide/v1/collectors/downloading-a-collector-installer/

collectorSize | The size of  the Collector you'd like to install. Options are nano, small (requires  2GB memory), medium (requires 4GB memory), large (requires 8GB memory).  Requires collector version 22.180 or higher. Defaults to small. | String | /setting/collectors/12/installers/Linux64?collectorSize=nano

However, when using Get-LogicMonitorCollectorInstaller it defaults to medium. Is it possible to include an option to select the size from nano/small/medium/large?

Thanks,

Andy

**Comment by wetling23** [comment]
Yup, I didn't get notification about this. It should be doable though.

**Comment by wetling23** [comment]
Updated the cmdlet, it should work for you once 1.0.1.10 is released.

**Comment by andy68man** [comment]
Thanks so much for doing this! :-)
