### ISSUE TITLE
Error in function - Remove-LogicMonitorDevice (No device was returned)

### ISSUE THREAD

**Issue by mishaal79** [wetling23/logicmonitor-posh-module#6]
Hey,

I'm trying to remove a logic monitor device with parameter displayname.
I get the following error,

![image](https://user-images.githubusercontent.com/41713723/61195887-6fe26700-a70e-11e9-8a94-1be6b279c7e5.png)

I've tried using **Get-LogicMonitorDevice** function with the same displayname and it returns a device.
In debugging the **Remove-LogicMonitorDevice** function I identified that a device is returned for the variable $device.

It skips the following conditional which causes the error.
```
 If ($device.id) {
                $Id = $device.id
                $resourcePath = "/device/devices/$Id"
            }
```
Please look into this and how it can be fix

Thank you.

**Comment by mishaal79** [comment]
Hello,

The reason for the above error is that $device is a list of devices instead of a single device.
The Get-LogicMonitorDevice function has been written such that it returns a list of psobjects where each device is stored in a list of items.
To access the the id of a device it should be:
```
 If ($device.items.id) {
                $Id = $device.items.id
                $resourcePath = "/device/devices/$Id"
            }
```
Hope you will fix this.
Thank you

**Comment by mishaal79** [comment]
Hello,

This bug is affecting other functions too.
## UpdateLogicMonitorDeviceProperty

The device id is being accessed in the same manner  and evaluates to null when assigning to resource path.

**Comment by wetling23** [comment]
Using the display name, how are you getting more than one device back? Get-LogicMonitorDevice uses  this: 

`filter=displayName:`"$DisplayName`"`

Which means that you are looking for the exact display name and LM requires display names to be unique in the account.

What version of the module and, specifically, Get-LogicMonitorDevice are you using?

**Comment by mishaal79** [comment]
I'm using the version v1.0.1.9 of the module and  V1.0.0.16 of the GetLogicMonitorDevice function.
The function doesn't return me more than one device instead it returns me a list in which there are items and those items have the id attribute.
I've changed the code as I mentioned earlier in the RemoveLogicMonitorDevice function and it works as expected without error.

**Comment by wetling23** [comment]
Updated (1.0.1.19). Sorry for the delay.
