### ISSUE TITLE
Request: Function Add-LogicMonitorDevice - Make parameter HostGroupID optional

### ISSUE THREAD

**Issue by mishaal79** [wetling23/logicmonitor-posh-module#7]
Hey,

I'm using your LM module to add devices using a PS script to LM.
I would like to have the hostgroupid to be an optional parameter as I would pick up the device into a dynamic group.

Thanks,
Mishal

**Comment by wetling23** [comment]
I will work on this. I will probably update the command to accept a hash table of properties instead of listing them separately.

**Comment by wetling23** [comment]
Done and done.

**Comment by mishaal79** [comment]
Thanks.
Appreciate it.
